import OpenAI from "openai";
import type { CodeCitation, ArchitectureOverview } from "@codeatlas/shared";

export interface RagContextChunk {
  filePath: string;
  name: string;
  kind: string;
  startLine: number;
  endLine: number;
  content: string;
  score?: number;
}

function getOpenAI() {
  const key = process.env.OPENAI_API_KEY;
  if (!key) return null;
  return new OpenAI({ apiKey: key });
}

function formatContext(chunks: RagContextChunk[]): string {
  return chunks
    .map(
      (c, i) =>
        `[${i + 1}] ${c.filePath} :: ${c.kind} ${c.name} (L${c.startLine}-L${c.endLine})\n\`\`\`\n${c.content.slice(0, 2500)}\n\`\`\``
    )
    .join("\n\n");
}

function citationsFromChunks(chunks: RagContextChunk[]): CodeCitation[] {
  return chunks.map((c) => ({
    filePath: c.filePath,
    name: c.name,
    kind: c.kind as CodeCitation["kind"],
    startLine: c.startLine,
    endLine: c.endLine,
    score: c.score,
  }));
}

function offlineAnswer(question: string, chunks: RagContextChunk[]): string {
  if (chunks.length === 0) {
    return `I couldn't find indexed code matching "${question}". Make sure the repository has finished indexing.`;
  }

  const lines = [
    `Based on the indexed codebase, here is what I found for: **${question}**\n`,
    ...chunks.slice(0, 5).map(
      (c, i) =>
        `### ${i + 1}. \`${c.name}\` (${c.kind})\n` +
        `- File: \`${c.filePath}\`\n` +
        `- Lines: ${c.startLine}-${c.endLine}\n` +
        `- Preview:\n\`\`\`\n${c.content.slice(0, 400)}\n\`\`\`\n`
    ),
    "\n_Running in offline demo mode (no OPENAI_API_KEY). Add an API key for full LLM answers._",
  ];
  return lines.join("\n");
}

export async function* streamRagAnswer(
  question: string,
  chunks: RagContextChunk[],
  systemExtra?: string
): AsyncGenerator<{ type: "token" | "citations" | "done"; data: unknown }> {
  const citations = citationsFromChunks(chunks);
  yield { type: "citations", data: citations };

  const openai = getOpenAI();
  if (!openai) {
    const answer = offlineAnswer(question, chunks);
    for (const word of answer.split(/(\s+)/)) {
      yield { type: "token", data: word };
    }
    yield { type: "done", data: { citations } };
    return;
  }

  const model = process.env.OPENAI_CHAT_MODEL || "gpt-4.1";
  const context = formatContext(chunks);

  const stream = await openai.chat.completions.create({
    model,
    stream: true,
    messages: [
      {
        role: "system",
        content: [
          "You are CodeAtlas AI, an expert code intelligence assistant.",
          "Answer using ONLY the provided code context when possible.",
          "Always cite file names, symbol names, and line ranges.",
          "Be precise, structured, and developer-friendly.",
          systemExtra || "",
        ]
          .filter(Boolean)
          .join(" "),
      },
      {
        role: "user",
        content: `Context:\n${context}\n\nQuestion: ${question}`,
      },
    ],
  });

  for await (const part of stream) {
    const token = part.choices[0]?.delta?.content;
    if (token) yield { type: "token", data: token };
  }

  yield { type: "done", data: { citations } };
}

export async function generateReadme(
  repoName: string,
  chunks: RagContextChunk[]
): Promise<string> {
  const openai = getOpenAI();
  const overview = chunks
    .slice(0, 20)
    .map((c) => `- ${c.filePath}: ${c.kind} ${c.name}`)
    .join("\n");

  if (!openai) {
    return [
      `# ${repoName}`,
      "",
      "## Overview",
      `AI-generated documentation draft for **${repoName}**.`,
      "",
      "## Key Symbols",
      overview || "- No indexed symbols yet.",
      "",
      "## Getting Started",
      "1. Install dependencies",
      "2. Configure environment variables",
      "3. Run the application",
      "",
      "_Generated by CodeAtlas AI (offline mode)_",
    ].join("\n");
  }

  const model = process.env.OPENAI_CHAT_MODEL || "gpt-4.1";
  const response = await openai.chat.completions.create({
    model,
    messages: [
      {
        role: "system",
        content: "Generate a clear, professional README.md from repository structure and code symbols.",
      },
      {
        role: "user",
        content: `Repository: ${repoName}\n\nSymbols:\n${overview}\n\nCode samples:\n${formatContext(chunks.slice(0, 8))}`,
      },
    ],
  });

  return response.choices[0]?.message?.content || "";
}

export async function generateApiDocs(chunks: RagContextChunk[]): Promise<string> {
  const openai = getOpenAI();
  const apiLike = chunks.filter((c) =>
    /route|controller|handler|api|endpoint|router/i.test(`${c.filePath} ${c.name}`)
  );

  if (!openai) {
    return [
      "# API Documentation",
      "",
      ...apiLike.slice(0, 15).map(
        (c) => `## ${c.name}\n- File: \`${c.filePath}\`\n- Lines: ${c.startLine}-${c.endLine}\n`
      ),
      apiLike.length === 0 ? "_No obvious API handlers found in index._" : "",
    ].join("\n");
  }

  const model = process.env.OPENAI_CHAT_MODEL || "gpt-4.1";
  const response = await openai.chat.completions.create({
    model,
    messages: [
      {
        role: "system",
        content: "Produce API documentation in Markdown from the provided handlers and routes.",
      },
      {
        role: "user",
        content: formatContext(apiLike.length ? apiLike : chunks.slice(0, 12)),
      },
    ],
  });

  return response.choices[0]?.message?.content || "";
}

export async function reviewCode(chunks: RagContextChunk[]): Promise<string> {
  const openai = getOpenAI();
  if (!openai) {
    const issues = chunks.slice(0, 8).map((c, i) => {
      const suggestions: string[] = [];
      if (c.content.length > 1200) suggestions.push("Consider splitting this large symbol into smaller units.");
      if (/TODO|FIXME/i.test(c.content)) suggestions.push("Contains TODO/FIXME markers.");
      if (/password|secret|api[_-]?key/i.test(c.content)) suggestions.push("Possible hardcoded secret — review carefully.");
      if (suggestions.length === 0) suggestions.push("Looks structurally fine; add unit tests if missing.");
      return `### ${i + 1}. ${c.filePath} :: ${c.name}\n${suggestions.map((s) => `- ${s}`).join("\n")}`;
    });
    return ["# AI Code Review (offline heuristics)", "", ...issues].join("\n");
  }

  const model = process.env.OPENAI_CHAT_MODEL || "gpt-4.1";
  const response = await openai.chat.completions.create({
    model,
    messages: [
      {
        role: "system",
        content:
          "Perform a constructive code review. Cover bugs, security, performance, readability, and suggest concrete improvements with file references.",
      },
      { role: "user", content: formatContext(chunks.slice(0, 15)) },
    ],
  });

  return response.choices[0]?.message?.content || "";
}

export function detectDuplicates(chunks: RagContextChunk[]): Array<{
  a: RagContextChunk;
  b: RagContextChunk;
  similarity: number;
}> {
  const pairs: Array<{ a: RagContextChunk; b: RagContextChunk; similarity: number }> = [];
  const normalize = (s: string) =>
    s.replace(/\s+/g, " ").replace(/["'`]/g, "").toLowerCase().slice(0, 500);

  for (let i = 0; i < chunks.length; i++) {
    for (let j = i + 1; j < chunks.length; j++) {
      const a = normalize(chunks[i].content);
      const b = normalize(chunks[j].content);
      if (a.length < 40 || b.length < 40) continue;
      const shorter = a.length < b.length ? a : b;
      const longer = a.length < b.length ? b : a;
      if (longer.includes(shorter) || levenshteinRatio(a, b) > 0.85) {
        pairs.push({ a: chunks[i], b: chunks[j], similarity: 0.9 });
      }
      if (pairs.length >= 25) return pairs;
    }
  }
  return pairs;
}

function levenshteinRatio(a: string, b: string): number {
  const m = Math.min(a.length, 200);
  const n = Math.min(b.length, 200);
  const s = a.slice(0, m);
  const t = b.slice(0, n);
  const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));
  for (let i = 0; i <= m; i++) dp[i][0] = i;
  for (let j = 0; j <= n; j++) dp[0][j] = j;
  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      dp[i][j] =
        s[i - 1] === t[j - 1]
          ? dp[i - 1][j - 1]
          : 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]);
    }
  }
  return 1 - dp[m][n] / Math.max(m, n);
}

export async function generateArchitectureOverview(
  repoName: string,
  files: string[],
  chunks: RagContextChunk[]
): Promise<ArchitectureOverview> {
  const layersMap = new Map<string, string[]>();
  for (const file of files) {
    const parts = file.split(/[\\/]/);
    const layer = parts.length > 1 ? parts[0] : "root";
    if (!layersMap.has(layer)) layersMap.set(layer, []);
    layersMap.get(layer)!.push(file);
  }

  const layers = [...layersMap.entries()].slice(0, 8).map(([name, layerFiles]) => ({
    name,
    description: `Contains ${layerFiles.length} files related to ${name}.`,
    files: layerFiles.slice(0, 12),
  }));

  const entryPoints = files.filter((f) =>
    /index\.(ts|js|tsx|jsx)|main\.(ts|js|py|go)|app\.(ts|js|tsx)|server\.(ts|js)/i.test(f)
  );

  const keyModules = chunks
    .filter((c) => c.kind === "class" || c.kind === "module")
    .slice(0, 10)
    .map((c) => ({ name: c.name, purpose: `Defined in ${c.filePath}` }));

  const openai = getOpenAI();
  if (!openai) {
    return {
      summary: `${repoName} appears organized into ${layers.length} top-level areas with ${files.length} indexed files.`,
      layers,
      entryPoints: entryPoints.slice(0, 10),
      keyModules,
    };
  }

  const model = process.env.OPENAI_CHAT_MODEL || "gpt-4.1";
  const response = await openai.chat.completions.create({
    model,
    messages: [
      {
        role: "system",
        content:
          "Summarize repository architecture in 2-4 sentences. Return plain text summary only.",
      },
      {
        role: "user",
        content: `Repo: ${repoName}\nLayers: ${layers.map((l) => l.name).join(", ")}\nEntry points: ${entryPoints.join(", ")}\nModules: ${keyModules.map((m) => m.name).join(", ")}`,
      },
    ],
  });

  return {
    summary: response.choices[0]?.message?.content || "",
    layers,
    entryPoints: entryPoints.slice(0, 10),
    keyModules,
  };
}
